# GitHub Action mis buildib projekti ja laeb GitHub releasidesse üles.

on: push

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - run: dotnet tool install --global Chickensoft.GodotEnv
      - run: godotenv addons install

      - name: Setup environment
        run: |
          echo "GODOT_ANDROID_KEYSTORE_RELEASE_PATH=${{ github.workspace }}/misc/debug.keystore" >> $GITHUB_ENV
          echo "GODOT_ANDROID_KEYSTORE_RELEASE_USER=androiddebugkey" >> $GITHUB_ENV
          echo "GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=android" >> $GITHUB_ENV

      - name: export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true

      - name: Set current date and commit name as env variable
        run: |
          echo "DATE=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
          echo "COMMIT_TITLE=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV
      - name: Write release body file
        run: echo "$(git log -1 --pretty=%B | tail -n+2)" > commit_body.txt

      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ env.DATE }}
          name: ${{ env.COMMIT_TITLE }}
          bodyFile: "commit_body.txt"
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
